# docker-compose.yml (Production Version)

version: '3.8'

services:
  api:
    # Указываем, что нужно собрать образ из Dockerfile в текущей директории
    build: .
    
    # Задаем имя для контейнера
    container_name: offer-api
    
    # Пробрасываем порт 8000 на локальной машине на порт 80 в контейнере
    ports:
      - "8000:8080"
      
    # Политика перезапуска контейнера
    restart: unless-stopped